# symbols:      

format = """
[](color_red)\
$directory\
[](bg:color_green fg:color_red)\
$git_branch\
[](bg:color_blue fg:color_green)\
$python\
[ ](fg:color_blue)
$cmd_duration
$character"""

palette = "gruvbox"

[palettes.glacier]
color_background = "#0c1115"
color_white = "#ffffff"
color_dark_gray = "#2e343c"
color_red = "#bd0f2f"
color_green = "#35a770"
color_yellow = "#fb9435"
color_blue = "#1f5872"
color_rust = "#bd2523"
color_pale_blue = "#778397"

[palettes.flannel]
color_background = "#090d13"
color_white = "#f3ebc3"
color_red = "#711817"
color_green = "#315c2b"
color_yellow = "#ee9711"
color_blue = "#29335c"
color_purple = "#925e78"
color_orange = "#dc650c"

[palettes.gruvbox]
color_background = "#282828"
color_white = "#ebdbb2"
color_red = "#cc241d"
color_green = "#98971a"
color_yellow = "#d79921"
color_blue = "#458588"
color_magenta = "#b16286"
color_cyan = "#689d6a"
color_gray = "#a89984"

[username]
show_always = true
style_user = "bg:color_rust fg:color_background"
style_root = "bg:color_rust fg:color_background"
format = "[ $user ]($style)"

[directory]
format = "[$path ]($style)"
style = "bg:color_red fg:color_white"
truncate_to_repo = false
truncation_length = 1000

[character]
success_symbol = "[](color_pale_blue)"
error_symbol = "[](color_pale_blue)"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:color_green fg:color_white"

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = ""
format = "[ $hash $tag]($style)"
style = "bg:color_green fg:color_white"

[python]
style = "bg:color_blue fg:color_white"
format = '[ via ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 5_000
format = '[$duration]($style) '
